### ISSUE TITLE
error: module is corrupted

### ISSUE THREAD

**Issue by ziflar** [4shadoww/usploit#1]
hi
first thx for this good job .i I really enjoyed
# i have error when i test [cloudflare_resolver](url) module
i run the tool with python 3.5 like this: 
`python3.5 usploit`
`use cloudflare_resolver`
`set target example.info`
`run`
i've this as error : 
```
error: module is corrupted
Traceback (most recent call last):
  File "core/libs/dns/resolver.py", line 174, in __init__
    rdclass, rdtype)
  File "core/libs/dns/message.py", line 353, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core/libs/dns/resolver.py", line 184, in __init__
    dns.rdatatype.CNAME)
  File "core/libs/dns/message.py", line 353, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Téléchargements/4shadoww-usploit-v1.3-alpha-42-g7158f55/4shadoww-usploit-7158f55/core/cmethods.py", line 214, in run
    modadd.run()
  File "/root/Téléchargements/4shadoww-usploit-v1.3-alpha-42-g7158f55/4shadoww-usploit-7158f55/modules/cloudflare_resolver.py", line 65, in run
    query = ipresolver.query(host, 'A')
  File "core/libs/dns/resolver.py", line 997, in query
    raise_on_no_answer)
  File "core/libs/dns/resolver.py", line 193, in __init__
    raise NoAnswer(response=response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: mail.example.info. IN A
```
how to fix it ??
What are the python dependencies for your project?
thank you fo your replay

**Comment by 4shadoww** [comment]
The project doesn't have any python dependencies. Other dependencies are listed on readme. It looks like unhandled exception, but I'm not sure why you get it. Maybe it does have something to do with your dns server. I think you should try another dns server. But I'll add exception for this error.
