### ISSUE TITLE
Curses Error

### ISSUE THREAD

**Issue by MeanMachine123** [4shadoww/usploit#3]
~/hakkuframework# ./hakku
Traceback (most recent call last):
  File "./hakku", line 55, in <module>
    from core import shell
  File "/root/hakkuframework/core/shell.py", line 9, in <module>
    from core import command_handler
  File "/root/hakkuframework/core/command_handler.py", line 6, in <module>
    from core import cmethods
  File "/root/hakkuframework/core/cmethods.py", line 9, in <module>
    import curses
  File "/usr/local/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by Atavic** [comment]
Possible causes:

- Python for Windows doesn't come with curses: https://github.com/pmbarrett314/curses-menu/issues/18#issuecomment-191015154

- Python being installed without support for curses: https://github.com/bpython/bpython/issues/564#issuecomment-330595512

- You must rebuild Python & modules against curses library: https://github.com/pyenv/pyenv/issues/240

**Comment by Aliyan-Haxo** [comment]
Chmod 7777 hakku && sudo python hakku 
Problem in root run this tool as root user.

**Comment by weedguy532** [comment]
What problem you have recently faced in this tool as i faced when i run the program.

**Comment by kalash99** [comment]
Hello,

Sorry but i dont know what are you talking about. Can u elaborate it please?
As i didn't sent any error conplain for any tool.

**Comment by weedguy532** [comment]
Can you explain me how stuff this tool works ?

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "/home/haider/Desktop/hakkuframework/./hakku", line 56, in <module>
    from core import scriptio
  File "/home/haider/Desktop/hakkuframework/core/scriptio.py", line 4, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
